---

- name: Checking servers date
  hosts: all
  remote_user: root
  roles:
    - common

- name: Configure app server
  hosts: app
  remote_user: root
  roles:
    - app

- name: Configure postgresql server
  hosts: postgresql
  remote_user: root
  roles:
    - postgresql