---

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-contrib
    - rsync

- name: Modify postgresql config
  command: sed -i -e 's/var\/lib\/postgresql\/12\/main/var\/postgresql\/12\/main/g' /etc/postgresql/12/main/postgresql.conf

- name: Sync postgresql data
  command: rsync -av --ignore-existing /var/lib/postgresql /var/

- name: Postgresql state (start on boot)
  service:
    name: postgresql
    state: started
    enabled: true
