---

- name: PostgreSQL apt repository
  shell: "{{ item }}"
  with_items:
    - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - apt-get update

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-{{ database_version }}
    - rsync

- name: Modify postgresql config
  shell: "{{ item }}"
  with_items:
    - sed -i -e 's/#listen_addresses = '"'"'localhost'"'"'/listen_addresses = '"'"'*'"'"'/g' /etc/postgresql/{{ database_version }}/main/postgresql.conf
    - sed -i -e 's/var\/lib\/postgresql\/{{ database_version }}\/main/var\/postgresql\/{{ database_version }}\/main/g' /etc/postgresql/{{ database_version }}/main/postgresql.conf
    - if ! grep -qF 'host all all {{ host_mask }} md5' /etc/postgresql/{{ database_version }}/main/pg_hba.conf; then echo 'host all all {{ host_mask }} md5' >> /etc/postgresql/{{ database_version }}/main/pg_hba.conf; fi;

- name: Sync postgresql data
  command: rsync -av --ignore-existing /var/lib/postgresql /var/

- name: Postgresql state (start on boot)
  service:
    name: postgresql
    state: started
    enabled: true
